/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Confirm: typeof import('./src/components/dialogs/Confirm.vue')['default']
    DialogProvider: typeof import('./src/components/DialogProvider.vue')['default']
    EditAuthor: typeof import('./src/components/dialogs/EditAuthor.vue')['default']
    EditPost: typeof import('./src/components/dialogs/EditPost.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
